services:
  # 1. Base de données
  postgres:
    image: postgres:15-alpine
    container_name: qcore_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Moteur de Calcul (Python)
  engine:
    build: ./apps/engine
    container_name: qcore_engine
    ports:
      - "8000:8000"
    volumes:
      - ./apps/engine:/app
    environment:
      - INTERNAL_API_SECRET=${INTERNAL_API_SECRET} 
      - PYTHONUNBUFFERED=1

  # 3. Studio (Préparation pour le futur ou le déploiement)
  # studio:
  #   build: 
  #     context: .
  #     dockerfile: apps/studio/Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - ./apps/studio/public/uploads:/app/apps/studio/public/uploads # Persistance des images
  #   environment:
  #     - DATABASE_URL=postgresql://quantum:password@postgres:5432/quantum_core
  #     - ENGINE_URL=http://engine:8000

volumes:
  postgres_data: